services:
  - type: web
    name: slack-voice-transcription
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DEEPGRAM_API_KEY
        value: 3e43c56e7bda92b003f12bcb46ae94dcd2c1b8f4
      - key: ZAPIER_WEBHOOK_URL
        value: your_zapier_webhook_url_here
